### ISSUE TITLE
Pin 1 indicator is not visible on manufactured boards due to silkscreen-to-mask clearance

### ISSUE THREAD

**Issue by mrnuke** [KiCad/Housings_SSOP.pretty#15]
The small line that is supposed to be the pin 1 indicator is too close to pad 1. Once soldermask clearance is taken into account, the silkscreen line would end up falling on bare FR4. This happens with 0.15 mm pad mask clearance.

I've tested Oshpark and seedstudio, and with both manufacturers, the pin1 indicator line is removed, and there is no way to identify the correct orientation of the footprint.

![img_20160725_210323](https://cloud.githubusercontent.com/assets/2610559/17125777/6b3f7bc6-52ab-11e6-9571-c84746c425cd.jpg)

**Comment by SchrodingersGat** [comment]
I have addressed this in https://github.com/KiCad/Housings_SSOP.pretty/pull/12

In future please feel free to make pull requests yourself to fix these issues :)

**Comment by CarlPoirier** [comment]
#12 is merged, so closing the issue. Thank you @mrnuke for reporting it.

**Comment by mrnuke** [comment]
These are manufacturing examples with git commit 2933ce3

![sssop_mfg](https://cloud.githubusercontent.com/assets/2610559/18031430/fb18ef68-6c94-11e6-81be-75ff28d51e50.JPG)
![ssop_mfg_scan](https://cloud.githubusercontent.com/assets/2610559/18031429/fb16a3a2-6c94-11e6-9f3d-970a3a33f808.png)

**Comment by mrnuke** [comment]
This specific example was manufactured at oshpark, with default kicad settings. oshpark's reference rendering is included below.

![mfg_render](https://cloud.githubusercontent.com/assets/2610559/18031446/ef19cde4-6c95-11e6-9f97-3d79731ceabc.png)

**Comment by michal777** [comment]
The mask clearance looks quite big. The footprints in the library has not the mask clearance defined so they use global settings. Maybe you have set it too large? I guess the setting should be zero and the manufacturer modifies mask according to his technology. I've used the the clearance set to zero and my boards looks fine (it may depend of manufacturer).

**Comment by mrnuke** [comment]
Mask clearance was set to 0.2 mm (8 mil). For oshpark, the tightest is 0.15mm (6 mil), and that sort of figure seems to be common among commodity manufacturers.

I see two ways to go about this.

1. Say mask clearance _must_ be at most so and so, and call this a user error.
2. Say that if a process is capable of manufacturing the feature size, the footprint should work with such process.

In my opinion, assuming a clearance of 0.15mm would work, a difference of 0.05mm should not cause such a dramatic outcome on a human-visible feature.

**Comment by SchrodingersGat** [comment]
@mrnuke can you post a screenshot of the silkscreen gerber layer you sent to OSHPark? Comparing the screenshot of the KiCad render with the boards you received, it looks to me like the silkscreen should have been on the final board. 

The middle part (SSOP-16_4.4x5.2) for example, the top line does not look like it should intersect with the solder mask at all - it looks like it has been completely removed, either by OSHPark or by KiCad when it was plotted...

**Comment by michal777** [comment]
Looks like they added their mask clearance to yours. Won't they accept just zero mask clearance on gerbers?

**Comment by mrnuke** [comment]
I uploaded the kicad_pcb file [1] directly. If you zoom in enough, there shouldn't be an overlap with soldermask (there's a clearance of 0.025mm/1mil).

[1] https://gist.github.com/mrnuke/10e3027b3196ba24202a1db71d90fb26
