### ISSUE TITLE
STEP files for 3D model?

### ISSUE THREAD

**Issue by evanshultz** [KiCad/Housings_SSOP.pretty#40]
https://github.com/KiCad/Housings_SSOP.pretty/blob/master/ST_MultiPowerSO-30.kicad_mod lists a STEP model for the 3D package:
![image](https://user-images.githubusercontent.com/1936989/29701266-964eeb20-891f-11e7-9536-6f129efe3a67.png)

This must be a mistake. KLC 10.4.i clearly says only WRL files are accepted.

I'll be submitting a PR to this repo soon, so if I'm not mistaken about this I can update this footprint at the same time.

**Comment by poeschlr** [comment]
You are right this is an oversight. (Or it has been committed before we clarified the KLC)

**Comment by evanshultz** [comment]
OK. I'll be submitting my PR in the not-too-distant future so if this isn't critical it was wait until then.
